
services:
  simple-web-service:
    image: devopsdockeruh/simple-web-service
    build: .
    command: server
    volumes:
      - ./text.log:/usr/src/app/text.log
    ports:
      - 4040:8080
    container_name: duh_sws_composed_server

