
services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    container_name: ex2_9_postgres
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=default-redis
    container_name: ex2_9_redis
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/
    ports:
      - 5000:5000
    container_name: ex2_9_front
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - REQUEST_ORIGIN=http://proxy/
      - REDIS_HOST=ex2_9_redis
      - POSTGRES_HOST=ex2_9_postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres
    container_name: ex2_9_back
  proxy:
    image: nginx:latest
    restart: unless-stopped
    container_name: ex2_9_proxy
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

volumes:
  database:
