
services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    container_name: ex2_8_postgres
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=default-redis
    container_name: ex2_8_redis
  frontend:
    build:
      context: ../ex1_12
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5000:5000
    container_name: ex2_8_front
  backend:
    build:
      context: ../ex1_13
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - REDIS_HOST=ex2_8_redis
      - POSTGRES_HOST=ex2_8_postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5001:8080
    depends_on:
      - postgres
    container_name: ex2_8_back
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: ex2_8_proxy
    ports:
      - 3000:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

volumes:
  database:
