
services:
  frontend:
    build:
      context: ../ex1_12
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: ex2_3_front
  backend:
    
    build:
      context: ../ex1_13
      dockerfile: Dockerfile
    ports:
      - 5001:8080
    container_name: ex2_3_back

